version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - "80:80"  # Доступ к pgAdmin через порт 80
    networks:
      - my-network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: IQnotion
    ports:
      - "5432:5432"  # Доступ к PostgreSQL через порт 5432
    networks:
      - my-network

networks:
  my-network: